{:config {:order 0, :description "tutorial recording for game", :name :for-game}
 :data
 [
  [:node-create [] :map]
  [:node-create [:main] :map]
  [:node-create [:main :my-counter] :map]
  [:transform-enable [:main :my-counter] :inc [{:io.pedestal.app.messages/topic [:my-counter]}]]
  [:node-create [:main :total-count] :map]
  [:value [:main :total-count] nil 2]
  [:node-create [:main :average-count] :map]
  [:value [:main :average-count] nil 0.67]
  [:node-create [:main :max-count] :map]
  [:value [:main :max-count] nil 1]
  [:node-create [:main :counters] :map]
  [:node-create [:main :counters "abc"] :map]
  [:value [:main :counters "abc"] nil 1]
  [:node-create [:main :counters "Me"] :map]
  [:node-create [:main :counters "xyz"] :map]
  [:value [:main :counters "xyz"] nil 1]
  [:node-create [:pedestal] :map]
  [:node-create [:pedestal :debug] :map]
  [:node-create [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time-max] nil 28]
  [:node-create [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time] nil 12]
  [:node-create [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-avg] nil 20]
  :break
  [:value [:main :total-count] 2 3]
  [:value [:main :average-count] 0.67 1]
  [:value [:main :max-count] 1 2]
  [:value [:main :counters "abc"] 1 2]
  [:value [:pedestal :debug :dataflow-time] 12 11]
  [:value [:pedestal :debug :dataflow-time-avg] 20 17]
  :break
  [:value [:main :total-count] 3 4]
  [:value [:main :average-count] 1 1.33]
  [:value [:main :max-count] 2 3]
  [:value [:main :counters "abc"] 2 3]
  [:value [:pedestal :debug :dataflow-time] 11 10]
  [:value [:pedestal :debug :dataflow-time-avg] 17 15]
  :break
  [:value [:main :total-count] 4 5]
  [:value [:main :average-count] 1.33 1.67]
  [:value [:main :counters "Me"] nil 1]
  [:value [:pedestal :debug :dataflow-time] 10 15]
  :break
  [:value [:main :total-count] 5 6]
  [:value [:main :average-count] 1.67 2]
  [:value [:main :counters "Me"] 1 2]
  [:value [:pedestal :debug :dataflow-time] 15 12]
  [:value [:pedestal :debug :dataflow-time-avg] 15 14]
  :break
  [:value [:main :total-count] 6 7]
  [:value [:main :average-count] 2 2.33]
  [:value [:main :counters "xyz"] 1 2]
  [:value [:pedestal :debug :dataflow-time] 12 10]
  :break
  [:value [:main :total-count] 7 8]
  [:value [:main :average-count] 2.33 2.67]
  [:value [:main :counters "Me"] 2 3]
  [:value [:pedestal :debug :dataflow-time] 10 11]
  [:value [:pedestal :debug :dataflow-time-avg] 14 13]
  :break
  [:value [:main :total-count] 8 9]
  [:value [:main :average-count] 2.67 3]
  [:value [:main :max-count] 3 4]
  [:value [:main :counters "Me"] 3 4]
  [:value [:pedestal :debug :dataflow-time] 11 15]
  :break
  [:value [:main :total-count] 9 10]
  [:value [:main :average-count] 3 3.33]
  [:value [:main :max-count] 4 5]
  [:value [:main :counters "Me"] 4 5]
  [:value [:pedestal :debug :dataflow-time] 15 12]
  :break
  [:value [:main :total-count] 10 11]
  [:value [:main :average-count] 3.33 3.67]
  [:value [:main :max-count] 5 6]
  [:value [:main :counters "Me"] 5 6]
  [:value [:pedestal :debug :dataflow-time] 12 13]
  :break
  [:value [:main :total-count] 11 12]
  [:value [:main :average-count] 3.67 4]
  [:value [:main :counters "abc"] 3 4]
  [:value [:pedestal :debug :dataflow-time] 13 10]
  :break
  [:value [:main :total-count] 12 13]
  [:value [:main :average-count] 4 4.33]
  [:value [:main :max-count] 6 7]
  [:value [:main :counters "Me"] 6 7]
  [:value [:pedestal :debug :dataflow-time] 10 11]
  :break
  [:value [:main :total-count] 13 14]
  [:value [:main :average-count] 4.33 4.67]
  [:value [:main :max-count] 7 8]
  [:value [:main :counters "Me"] 7 8]
  [:value [:pedestal :debug :dataflow-time] 11 14]
  :break
  [:value [:main :total-count] 14 15]
  [:value [:main :average-count] 4.67 5]
  [:value [:main :max-count] 8 9]
  [:value [:main :counters "Me"] 8 9]
  [:value [:pedestal :debug :dataflow-time] 14 12]
  :break
  [:value [:main :total-count] 15 16]
  [:value [:main :average-count] 5 5.33]
  [:value [:main :counters "abc"] 4 5]
  [:value [:pedestal :debug :dataflow-time] 12 11]
  [:value [:pedestal :debug :dataflow-time-avg] 13 12]
 ]}