{:config {:order 0, :description "first login recording", :name :login-1}
 :data
 [
  [:node-create [] :map]
  [:node-create [:login] :map]
  [:node-create [:login :name] :map]
  [:transform-enable [:login :name] :login [{:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:login :name], :io.pedestal.app.messages.param/value {}} {:io.pedestal.app.messages/type :set-focus, :io.pedestal.app.messages/topic :io.pedestal.app.messages/app-model, :name :game}]]
  :break
  [:value [:login :name] nil "michael"]
  :break
  [:value [:login :name] "michael" nil]
  [:transform-disable [:login :name] :login [{:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:login :name], :io.pedestal.app.messages.param/value {}} {:io.pedestal.app.messages/type :set-focus, :io.pedestal.app.messages/topic :io.pedestal.app.messages/app-model, :name :game}]]
  [:node-destroy [:login :name] :map]
  [:node-destroy [:login] :map]
  [:node-create [:main] :map]
  [:node-create [:main :my-counter] :map]
  [:transform-enable [:main :my-counter] :add-points [{:io.pedestal.app.messages/topic [:my-counter], :io.pedestal.app.messages.param/points {}}]]
  [:node-create [:main :total-count] :map]
  [:value [:main :total-count] nil 6]
  [:node-create [:main :average-count] :map]
  [:value [:main :average-count] nil 2]
  [:node-create [:main :max-count] :map]
  [:value [:main :max-count] nil 4]
  [:node-create [:main :counters] :map]
  [:node-create [:main :counters "abc"] :map]
  [:value [:main :counters "abc"] nil 4]
  [:node-create [:main :counters "michael"] :map]
  [:node-create [:main :counters "xyz"] :map]
  [:value [:main :counters "xyz"] nil 2]
  [:node-create [:main :player-order] :map]
  [:node-create [:main :player-order "abc"] :map]
  [:value [:main :player-order "abc"] nil 0]
  [:node-create [:main :player-order "xyz"] :map]
  [:value [:main :player-order "xyz"] nil 1]
  [:node-create [:main :player-order "michael"] :map]
  [:value [:main :player-order "michael"] nil 2]
  [:node-create [:main :clock] :map]
  [:value [:main :clock] nil 5]
  [:node-create [:main :add-bubbles] :map]
  [:value [:main :add-bubbles] nil {:clock 5, :count 3}]
  [:node-create [:pedestal] :map]
  [:node-create [:pedestal :debug] :map]
  [:node-create [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time-max] nil 43]
  [:node-create [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time] nil 15]
  [:node-create [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-avg] nil 22]
  :break
  [:value [:main :total-count] 6 7]
  [:value [:main :average-count] 2 2.33]
  [:value [:main :max-count] 4 5]
  [:value [:main :counters "abc"] 4 5]
  [:value [:pedestal :debug :dataflow-time] 15 14]
  :break
  [:value [:main :clock] 5 6]
  [:value [:main :add-bubbles] {:clock 5, :count 3} {:clock 6, :count 3}]
  :break
  [:value [:main :total-count] 7 8]
  [:value [:main :average-count] 2.33 2.67]
  [:value [:main :counters "xyz"] 2 3]
  :break
  [:value [:main :total-count] 8 9]
  [:value [:main :average-count] 2.67 3]
  [:value [:main :max-count] 5 6]
  [:value [:main :counters "abc"] 5 6]
  [:value [:pedestal :debug :dataflow-time] 14 28]
  :break
  [:value [:main :clock] 6 7]
  [:value [:main :add-bubbles] {:clock 6, :count 3} {:clock 7, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 28 11]
  [:value [:pedestal :debug :dataflow-time-avg] 22 21]
  :break
  [:value [:main :total-count] 9 10]
  [:value [:main :average-count] 3 3.33]
  [:value [:main :max-count] 6 7]
  [:value [:main :counters "abc"] 6 7]
  [:value [:pedestal :debug :dataflow-time] 11 29]
  [:value [:pedestal :debug :dataflow-time-avg] 21 22]
  :break
  [:value [:main :clock] 7 8]
  [:value [:main :add-bubbles] {:clock 7, :count 3} {:clock 8, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 29 13]
  [:value [:pedestal :debug :dataflow-time-avg] 22 21]
  :break
  [:value [:main :total-count] 10 11]
  [:value [:main :average-count] 3.33 3.67]
  [:value [:main :max-count] 7 8]
  [:value [:main :counters "abc"] 7 8]
  [:value [:pedestal :debug :dataflow-time] 13 25]
  :break
  [:value [:main :total-count] 11 12]
  [:value [:main :average-count] 3.67 4]
  [:value [:main :counters "xyz"] 3 4]
  [:value [:pedestal :debug :dataflow-time] 25 22]
  :break
  [:value [:main :total-count] 12 16]
  [:value [:main :average-count] 4 5.33]
  [:value [:main :counters "michael"] nil 4]
  [:value [:pedestal :debug :dataflow-time] 22 13]
  :break
  [:value [:main :clock] 8 9]
  [:value [:main :add-bubbles] {:clock 8, :count 3} {:clock 9, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 13 12]
  [:value [:pedestal :debug :dataflow-time-avg] 21 20]
  :break
  [:value [:main :total-count] 16 17]
  [:value [:main :average-count] 5.33 5.67]
  [:value [:main :max-count] 8 9]
  [:value [:main :counters "abc"] 8 9]
  [:value [:pedestal :debug :dataflow-time] 12 25]
  [:value [:pedestal :debug :dataflow-time-avg] 20 21]
 ]}